liquality/wallet

package-lock.json, src/background.js, src/store/actions/enableAssets.js, src/store/actions/updateFiatRates.js, src/store/getters.js, src/store/mutations.js, src/views/Swap/Swap.vue
Also overrides the fiat rates instead of simply resetting based on response. This preserves any existing fiat rates
Fiat rates were not retrieved for assets that are not preset in the wallet. 
Selecting a unknown ERC20 in swap would show wrong fiat price
https://www.notion.so/ERC20-Providers-Broken-8529a717fbeb4b90b32514a8066e0f69
0
=> Retrieve fiat rates on selection in Swap

src/views/Swap/Swap.vue, tests/integration/swipe_testnet.spec.js
For swaps where the destination (receive) side does not require a fee to be paid, it should not be displayed to the user
https://www.notion.so/ERC20-Providers-Broken-8529a717fbeb4b90b32514a8066e0f69
0
=> Swap: do not count fee in receive when not required

src/swaps/fastbtc/SwapDetails.vue
Remove Slippage for fastBTC service provider from all places
https://www.notion.so/fastBtC-don-t-show-slippage-on-swap-screen-13af8d7d4c20498fa8df301fac0b3f67
0
=> fix: Remove slippage from SWAP screen for fastBTC

src/build.config.js, tests/Pages/OverviewPage.js, tests/e2e/03_receive.spec.js
Solana is not quite ready for prod and should be disabled as default until we test mainnet
When creating a new wallet:
- Solana coin should not display on the assets page
- Both testnet and mainnet
- It can still be accessed in "manage assets"
=> fix: disable sol as default asset

src/views/Send/Send.vue
BTC send fee was not being displayed. There was an error in the code
https://www.notion.so/Fee-missing-4e3caa2a6e01470ea4d6e1a214bb8d5b
=> fix: btc send fee had error while calculating

src/broker/Background.js, src/store/actions/executeRequest.js, src/store/actions/requestPermission.js, src/views/Details/TransactionDetails.vue, src/views/PermissionSignPsbt.vue
Instead of retrieving the currently connected account when the request is being executed,
send the accountId through the permission request. This ensures the request is locked to the correct account when it is accepted and also allows us to display account information in the permission requests in the future
Test injection with dapps (regression)
I tested sovryn continues to work and connect to correct account
=> fix: pass through accountId to permission requests

src/views/Settings.vue, tests/e2e/09_menu_options.spec.js
I would not say RSK is "ethereum based" but that it is an EVM bitcoin sidechain with Web3 compatible dapps. I think changing this phrase from calling it "ethereum based network" to "Web3 network" is more in line with what this setting is for.
=> "ethereum based network" -> Web3 network

README.md
testing integration to linear.app
https://linear.app/liquality/issue/LIQ-21/integrate-github-with-linear
the branch name `b0b/liq-21-integrate-github-with-linear` is supposed to be detected by linear.app
nope
=> test: linear.app integration

src/components/CustomFees.vue, src/views/Send/Send.vue
#Linear Ticket
LIQ-121
[Linear Issue](https://linear.app/liquality/issue/LIQ-121/in-case-of-rsk-send-user-set-custom-fees-it-displays-in-scientific)
Incorrect display (scientific notation) of custom fee.
Using `prettyFee` instead of `customFee`
0
This issue is also fixed as part of the PR (NaN value when custom fee field is empty is now changed to 0).
=> fix: custom fees visuals

package-lock.json, package.json
Update cryptoassets verions from 1.7.1 to 1.7.2.
Important: @liquality/hw-web-bridge is still using cryptoassets 1.7.1 !
=> feat: cryptoassets 1.7.2

src/background.js
[LIQ-1049](https://linear.app/liquality/issue/LIQ-1049/[amplitude]-send-serviceprovider-in-swap-transaction-status)
=> feat: LIQ-1049, swap history send provider

src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
Fix incorrect accountID in ERC20 to Native Boost.
=> fix: inccorect accountId on erc20 to native swaps

src/store/getters.js
[LIQ-1238](https://linear.app/liquality/issue/LIQ-1238/boost-wrong-accountid)
=> fix: prevent account and asset chain mismatch

src/views/Splash.vue
Expected: Starting screen should be password if wallet is locked
Actual: Starting screen was the splash screen with "Open wallet" button
=> fix: Locked wallet should show password screen

src/views/Swap/SwapProvidersInfoModal.vue
Duplication of Boost in the SwapProvidersInfoModal
=> fix: remove duplicate providers on info modal

src/components/BoostActivateBridgeAsset.vue, src/views/Swap/Swap.vue
[LIQ-1062](https://linear.app/liquality/issue/LIQ-1062/user-need-to-increase-the-input-amount-to-see-the-liquidity-between)
Blocks boost swaps when bridge asset is disabled
=> feat: show error when bridge asset of boost is disabled

src/views/Swap/Swap.vue
[LIQ-1291](https://linear.app/liquality/issue/LIQ-1291#comment-68afa2e4)
Hides error 'Please increase amount. It is below minimum.' before first update of swipe providers for assets that have np dollar value (in most cases Rootstock ERC20s).
=> feat: prevent zero error for non dollar value assets

src/views/Swap/Swap.vue
[LIQ-1393](https://linear.app/liquality/issue/LIQ-1393/liquality-boost-or-reduce-the-min-for-pweth-to-btc-so-that-user-can)
[LIQ-1062](https://linear.app/liquality/issue/LIQ-1062/user-need-to-increase-the-input-amount-to-see-the-liquidity-between)
=> feat: improve minimum amount logic for boosts

src/background.js
feat: LIQ-1470 - track Opt In events separately
https://linear.app/liquality/issue/LIQ-1471/[amplitude]-track-create-wallet-vs-import-with-seed-phrase-existing
https://linear.app/liquality/issue/LIQ-1470/[amplitude]-track-just-opt-in-event-separately
=> feat: LIQ-1470 - track create wallet and Import with seed phrase

src/background.js
the `updateBalances` action is dispatched twice during wallet unlock:
1. once during `Wallet.vue` component creation (in `created()`)
2. once in the `UNLOCK_WALLET` listener in `background.js`
When the wallet is unlocked the first component is always `Wallet` so we can get rid of the dispatch that happens in `UNLOCK_WALLET`
=> fix: get rid of duplicate balance update dispatching

src/views/Details/NFTCollectionList.vue, src/views/Swap/Accounts.vue
- remove NFT from the swap asset list
- make the top bar fixed on the scroll
[LIQ-1556](https://linear.app/liquality/issue/LIQ-1556/title-bar-and-buttons-on-the-bottom-should-be-sticky-on-nft-screens)
[LIQ-1553](https://linear.app/liquality/issue/LIQ-1553/nft-option-should-not-display-under-select-asset-for-swap)
=> NFT Updates

src/locales/en/common.json
Labels in the dropdown menu in Settings for selecting the language should appear translated in their native language.
=> Labels should appear in their native language

src/locales/en/pages.json, src/views/CustomToken.vue
=> LIQ-179 | Added user notification for existing custom tokens

src/locales/cb/liquality_errors.json, src/locales/en/components.json, src/locales/en/liquality_errors.json, src/locales/es/liquality_errors.json, src/locales/ph/liquality_errors.json, src/locales/pt/liquality_errors.json, src/locales/zh/liquality_errors.json, src/utils/localization.js
What this PR does the following
1. Move error translation files from wallet core to wallet
2. Update message copy for 'pair not traded' [see context](https://linear.app/liquality/issue/COR-77#comment-edd66623)
=> fix: localize error translations

src/components/ActivityFilter.vue, src/components/NoTransactionsFound.vue, src/components/TransactionList.vue, src/locales/en/common.json, src/views/Wallet/WalletActivity.vue
This PR fixes issues;
- Activity filters for all options
- Rendering of filters where a user cannot see filters again after selection any filter option
- Wrong Data returned on filtering
- https://github.com/liquality/wallet-core/pull/256
=> Activity filter fixes

src/locales/es/pages.json
This change has already been done in Crowdin.
=> Change the word Cadenas to Redes in Spanish

package.json, src/manifest.json, src/views/Send/Send.vue, src/views/Send/SendNFT.vue
=> Ext 253/gas fee handler
