liquality/wallet

.husky/pre-commit, package-lock.json, package.json, src/views/Swap.vue
=> fix: remove standard package and change pre-commit hook

package-lock.json, package.json, src/assets/icons/close.svg, src/assets/scss/_overrides.scss, src/assets/scss/style.scss, src/assets/scss/tooltip.scss, src/components/DetailsContainer.vue, src/components/FeeSelector.vue, src/components/NavBar.vue, src/manifest.json, src/views/Enable.vue, src/views/Permission.vue, src/views/PermissionSend.vue, src/views/PermissionSign.vue, src/views/Receive.vue, src/views/Send.vue, src/views/Swap.vue
- Removed warning message in all screens
- Fixed review screens with new design for send and swap
- Modified receive screen according to design
- Fixed sizes and spaces in send and swap screens
=> Feature UI changes

src/views/SeedPhrase/LoginPhrase.vue
1) Changed from a image component to a :src image, and computed the component above the methods
=> Fixed the gradient on the logo:

src/store/actions/newSwap.js
=> fix param secretHash

src/views/ImportWallet.vue, src/views/Onboarding/OnboardingHome.vue, src/views/Onboarding/OnboardingPassword.vue, src/views/Onboarding/OnboardingSetup.vue, src/views/Onboarding/SeedPhrase/ConfirmSeed.vue, src/views/Onboarding/SeedPhrase/Congratulations.vue, src/views/Onboarding/SeedPhrase/LoginPhrase.vue, src/views/Onboarding/SeedPhrase/PhraseReveal.vue, src/views/Onboarding/SeedPhrase/Warning.vue
Fixes to UI:
-Confetti changed
-onboarding flow has been redone per Thessy request
-Other small changes from the figma
=> Pixel perfect

package-lock.json, package.json, src/components/WalletAccounts.vue, tests/integration/Pages/HomePage.js, tests/integration/Pages/OverviewPage.js, tests/integration/Pages/PasswordPage.js, tests/integration/Pages/SearchAssetPage.js, tests/integration/Pages/SendPage.js, tests/integration/Pages/TransactionDetailsPage.js, tests/integration/testnet/send_testnet.spec.js, tests/integration/testnet/testNetNetwork.spec.js, tests/utils/TestDataUtils.js
- SEND test cases
- SEND tests with invalid format address * exceeded limit error message checks
- Added Page in tests  for each view
- Generate random ETH and BTC address for tests
=> [TEST] - SEND feature

.github/workflows/build-test-release.yml, .github/workflows/build-test.yml
- Save screenshots
for tooltip test
=> Validate Network fee and speed tooltips

.github/workflows/build-test-release.yml, .github/workflows/build-test.yml, package.json, src/manifest.json, tests/integration/testnet/send_testnet.spec.js, tests/integration/testnet/testNetNetwork.spec.js
- Bump version 0.34.3
- Fix Browser launch issue on ubuntu
- Updated the Ci config to install other ubuntu packages
-
=> Wallet version v0.34.3

.github/workflows/build-test-release.yml, package.json, src/manifest.json
- Updated the release CI to run tests
=> v0.34.6 release

.github/workflows/build-test-release.yml, .github/workflows/build-test.yml, package.json, tests/integration/testnet/create_wallet_testnet.spec.js, tests/integration/testnet/import_wallet_testnet.spec.js, tests/integration/testnet/receive_testnet.spec.js, tests/utils/TestUtils.js
- Run all tests against PR creation
- Run selected tests against build release tag
- Added moch grep
=> [Test]- Mocha grep Mainnet tests

.github/workflows/build-test-release.yml, .github/workflows/build-test.yml, .mocharc.yml, package.json, tests/integration/Pages/OverviewPage.js, tests/integration/Pages/ReceivePage.js, tests/integration/Pages/SwapPage.js, tests/integration/testnet/receive_testnet.spec.js, tests/integration/testnet/swipe_testnet.spec.js
- Validate href value in Receive screen
=> [TEST]-Added BNB receive test

.gitignore, src/views/Send/Send.vue, tests/integration/Pages/OverviewPage.js, tests/integration/Pages/SendPage.js, tests/integration/testnet/send_testnet.spec.js
=> [TEST]-Added NEAR send test case

tests/integration/Pages/ReceivePage.js, tests/integration/testnet/receive_testnet.spec.js
- Validate NEAR receive QA & address validations
=> [TEST]-Added NEAR Receive and validate receive details.

.github/workflows/build-test-release.yml, .github/workflows/build-test.yml, src/views/ImportWallet.vue, tests/integration/Pages/HomePage.js, tests/integration/Pages/SendPage.js, tests/integration/testnet/import_wallet_testnet.spec.js
- Added 24 words import wallet tests
-  Added TWENTY_FOUR_SEEDS as environment variable
=> [TEST] - Added 24 seed words import wallet

tests/integration/testnet/import_wallet_testnet.spec.js, tests/utils/TestDataUtils.js
- Validate Test import wallet with 11 words
=> [Test]-Added test to validate with 11 words

src/views/Account.vue, src/views/Onboarding/SeedPhrase/PhraseReveal.vue, src/views/Onboarding/SeedPhrase/Warning.vue, tests/integration/Pages/HomePage.js, tests/integration/Pages/SearchAssetPage.js, tests/integration/testnet/menu_options.spec.js, tests/integration/testnet/swipe_testnet.spec.js
- validate backup seed option test
=> [TEST]- Backup seed setting test

src/store/actions/unlockWallet.js, src/store/factory/client.js, src/store/migrations.js, src/store/mutations.js, src/store/state.js, src/store/utils.js
…se legacy coin type other way apply the new one
=> feat: Rsk legacy derivation path

src/components/ListItem.vue, src/utils/asset.js, tests/Pages/SwapPage.js, tests/integration/create_wallet.spec.js, tests/integration/swipe_testnet.spec.js
NEAR to BTC swap test
- validate swap quote model screen
0
=> feat: Near to btc swap checkl

src/store/actions/createWallet.js, src/store/factory/client.js, src/store/migrations.js, src/store/utils.js, tests/integration/create_wallet.spec.js, tests/integration/import_wallet.spec.js, tests/integration/menu_options.spec.js, tests/integration/receive.spec.js, tests/integration/send_testnet.spec.js, tests/integration/swipe_testnet.spec.js
=> fix: Check balance for erc20 tokens on rsk as well to determine correct derivation path

src/components/WatsNewModal.vue, tests/Pages/OverviewPage.js, tests/integration/add_custom_token.spec.js, tests/integration/create_wallet.spec.js, tests/integration/import_wallet.spec.js, tests/integration/menu_options.spec.js, tests/integration/receive.spec.js, tests/integration/send_testnet.spec.js, tests/integration/swipe_testnet.spec.js
=> added close modal function to close news modal

src/components/TransactionList.vue, src/views/CustomToken.vue, src/views/ManageAssets.vue, tests/integration/add_custom_token.spec.js
https://www.notion.so/Wallet-Automation-test-to-Add-custom-token-fetch-details-23c707c747eb4d349f9cb75711fe2390
0
=> feat: Custom token scripts

src/components/NavBar.vue, src/views/Account.vue, tests/integration/create_wallet.spec.js, tests/integration/derived_path.spec.js
https://www.notion.so/Wallet-Automated-tests-to-validate-derived-paths-for-chains-f5289b9b2dfc417398f9b3a3178a90bf
=> feat: derivation path tests

src/views/PermissionSend.vue
=> Feat: Integrate custom fees

package-lock.json, package.json, src/manifest.json, src/store/migrations.js
Added new migration to force update for rsk legacy derivation path
https://www.notion.so/30ca4d49f3844a0fabdf4141f8a8bccc?v=44514edd52d14b719a9dec59d60147dd&p=900f7d3ace7d4d338fdf7a85306c09d9
=> Added new migration to force update for rsk legacy derivation path

src/swaps/liquality/SwapDetails.vue
=> fix: Retry button in tx swap details to call the atomic agent

src/components/ChainDropdown.vue, src/views/Enable.vue, tests/Pages/OverviewPage.js, tests/integration/custom_fee.spec.js, tests/integration/dapp_injection.spec.js
- ETH injection with UNISWAP dapp
- Validate Connect request woks between liquality and uniswap
=> feat: Dapp Injection test (UNISWAP app)

package-lock.json, package.json, src/components/WatsNewModal.vue, src/manifest.json, src/store/actions/updateBalances.js
- https://www.notion.so/Wallet-can-t-access-to-RSK-old-address-when-update-the-wallet-900f7d3ace7d4d338fdf7a85306c09d9
- https://www.notion.so/Copy-What-s-New-Card-at-opening-078b35637ffd4999912999b128ea3eee
=> fix: Bug Fixes related to wrong address in rsk accounts and update the what's new card copy text

src/views/ManageAssets.vue, tests/integration/04_send.spec.js
Link issue
https://www.notion.so/wallet-update-the-release-notes-URL-on-assert-view-95708843a13d4763acd949a40b43529e
0
=> fix: Learn how link fixed

src/views/Swap/Swap.vue
=> liquidity-fix-rebranched

src/swaps/oneinch/info.json, src/views/Swap/SwapInfo.vue
fix: fastBTC don't show slippage
https://www.notion.so/Copy-changes-1inch-8e82411f16714d8faea0988769b555d1
https://www.notion.so/fastBtC-don-t-show-slippage-on-awap-screen-13af8d7d4c20498fa8df301fac0b3f67
=> fix: 1inch copy

src/utils/asset.js
Fix ARBITRUM custom token details
https://www.notion.so/ARBITRUM-custom-token-fetch-not-working-0dfcf663b9604b57babb0571317532e8
=> fix: Fix ARBITRUM custom token details

src/utils/asset.js, src/views/Receive.vue
=> fix: Solana Links

tests/Pages/OverviewPage.js, tests/e2e/07_add_custom_token.spec.js
- Just ARBITRUM custom token test against Mainnet
=> feat: Added ARBITRUM custom token test

src/utils/asset.js, src/views/PermissionSend.vue
Use custom fee as multiplier 
https://www.notion.so/Unable-to-set-custom-fees-on-uniswap-dapp-a9167540fd864fcb85537a3126a920f6
=> fix: Handle custom fees

.env, .github/workflows/build-smoke-tests.yml, .github/workflows/build-test-mainnet.yml, .github/workflows/build-test-testnet.yml, .github/workflows/release.yml, src/utils/asset.js
-  Set the VUE_APP_AMPLITUDE_API_KEY as env
- Fix the Puppeter Docker image version with 1.0.6
- Rename the Release ci name
=> feat: VUE_APP_AMPLITUDE_API_KEY

src/store/factory/client.js
Add infura provider for arbitrum
=> fix: changed arbitrum rpc provider

.github/workflows/release.yml
=> fix: save VUE_APP_AMPLITUDE_API_KEY into .env

.github/workflows/release.yml
- Don't run npm build for prod if the tag is patch
=> fix: fix the Ci config for Dev and Prod releases

tests/Pages/OverviewPage.js, tests/e2e/03_receive.spec.js
=> feat: SOLANA test

src/background.js, src/views/Account.vue, src/views/Settings.vue
- Send analytics
- Hold assets event after user selects the chain if balance is greater than 0
- Add Custom token events
- Rename other events / actions
https://www.notion.so/Implement-Wallet-Analytics-51e263d76eae4edaaaa5821ef98baef1
=> feat: Send / Hold assets events

src/background.js
=> fix: fix the Send event categories

.env, .github/workflows/release.yml, src/background.js, src/views/Account.vue, src/views/Receive.vue
- Receive screen copy address event
- Refresh balance on-chain screen event
- Swap update status
- Send update status
- Send event renamed
- Added DEV token for Amplitude for Dev extension
=> feat: Refresh balance & Copy address from Receive screen events added

src/views/Account.vue, src/views/Send/Send.vue
fix: Rename the hold balance event
=> feat: Adding user on Send screen event

src/views/Send/Send.vue, src/views/Swap/Swap.vue
=> feat: Added SWAP screen event

src/background.js, src/components/NavBar.vue, src/views/Onboarding/SeedPhrase/LoginPhrase.vue, src/views/Receive.vue, src/views/Settings.vue
- Improve SWAP event labels
- Improve hamburgers clicks
- Added user clicks on receive screen
https://www.notion.so/Implement-Wallet-Analytics-51e263d76eae4edaaaa5821ef98baef1
=> feat: Improve SWAP labels

src/background.js
- Updated the labels for events
=> feat: Refactor events to support dashboards

tests/Pages/SwapPage.js, tests/e2e/05_swap.spec.js
- Negative SWAP message validation on SWAP screen
=> feat: Added Negative swap warn message

src/background.js, src/views/Account.vue, tests/Pages/SendPage.js, tests/Pages/SwapPage.js, tests/e2e/05_swap.spec.js, tests/e2e/08_custom_fee.spec.js
=> feat: update balance event

src/router/index.js, src/views/ImportWallet.vue, src/views/Onboarding/OnboardingSetup.vue, tests/e2e/06_derived_path.spec.js
Mnemonics were not validated on import
https://www.notion.so/30ca4d49f3844a0fabdf4141f8a8bccc?v=480df463805f4c74a4106b4a294be001&p=dac68dd41c664f24a7b4e657fc546281
Using `bip39` we can validate the word set, length and checksum
- Tried some invalid
=> feat: validate mnemonic on import

tests/e2e/02_import_wallet.spec.js
=> feat: Added BIP39 test cases

tests/e2e/13_rsk_bridge_injection.spec.js, tests/e2e/14_swap_sovryn_amm.js
- RSK Sovryan Bridge injection
=> feat: RSK bridge injection

tests/Pages/SwapPage.js, tests/e2e/11_dapp_injection.spec.js, tests/e2e/rsk_tests/10_fastbtc_swap.spec.js, tests/e2e/rsk_tests/13_rsk_bridge_injection.spec.js, tests/e2e/rsk_tests/14_swap_sovryn_amm.js
- RSK tests in separate folder
=> feat: Separate RSK tests

tests/e2e/rsk_tests/06_derived_path.spec.js
=> feat: Added derivation path tests

src/store/factory/client.js, src/swaps/oneinch/OneinchSwapProvider.js, src/utils/asset.js
Update the polygon rpc to stay reliable
=> fix: update polygon rpc

src/views/CustomToken.vue
LIQ-513
LIQ-517
LIQ-540
https://linear.app/liquality/issue/LIQ-540/terra-bridge-transaction-from-luna-to-eth-on-confirm-page-an-error-is
https://linear.app/liquality/issue/LIQ-517/if-user-adds-wluna-token-then-original-luna-token-get-named-as-wluna
https://linear.app/liquality/issue/LIQ-513/ui-issue-received-assets-for-example-wluna-are-not-displaying-properly
=> fix: Symbol duplication

src/views/CustomToken.vue
=> fix: Correct statement

src/views/Receive.vue
=> fix: correct terra QR uri

.github/workflows/build-test-mainnet.yml, .github/workflows/build-test-testnet.yml, .github/workflows/pullrequests.yml, tests/Pages/SendPage.js, tests/e2e/05_swap.spec.js, tests/e2e/17_uniswap_dapp_injection.spec.js, tests/e2e/18_sushi_dapp_injection.spec.js
https://linear.app/liquality/issue/LIQ-617/[test]-sushi-dapp-injection-test
LIQ-617
=> fix: LIQ-617 test, ci fixes

src/background.js, tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
=> feat: LIQ-628 - SEND EVENTS improved

src/background.js
=> fix: LIQ-628 - rename

.github/pull_request_template.md, package.json, src/manifest.json, tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
#Linear Ticket
https://linear.app/liquality/issue/LIQ-613/[test]-terra-money-dapp-injections-tests
=> feat: test terra money finance dapp tests

tests/e2e/05_swap.spec.js, tests/e2e/17_uniswap_dapp_injection.spec.js, tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
=> fix: fix some tests

src/utils/asset.js, tests/Pages/SwapPage.js, tests/e2e/05_swap.spec.js
=> fix: Fix receive zero amount

src/views/CustomToken.vue
LIQ-507
LIQ-518
LIQ-578
LIQ-623
=> fix: Display error for existing symbol only if assets exists

src/views/Accounts/ChainAccounts.vue, src/views/Experiments.vue, tests/Pages/OverviewPage.js, tests/Pages/PasswordPage.js, tests/e2e/13_manage_accounts.spec.js, tests/utils/TestUtils.js
=> feat: LIQ-666 multi account tests enabled

tests/Pages/PasswordPage.js, tests/e2e/terra_tests/21_terra_anchor_dapp.spec.js, tests/utils/TestUtils.js
#Linear Ticket
Disable notifications
=> fix: Fix terra dapp tests

package-lock.json, package.json, src/manifest.json
#Linear Ticket
updated package hw-web-bridge
=> fix: update hw-bridge package

tests/e2e/05_swap.spec.js, tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
=> fix: fix RBTC to BTC test fix

tests/e2e/11_oneinch_dapp_injection.spec.js, tests/e2e/16_uniswap_provider.spec.js, tests/e2e/17_uniswap_dapp_injection.spec.js, tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
=> fix: fix uniswap flaky tests

src/swaps/views/Timeline.vue
=> fix: overflow in timeline details

.github/pull_request_template.md, src/views/CustomToken.vue, tests/e2e/05_swap.spec.js, tests/e2e/13_manage_accounts.spec.js, tests/e2e/rsk_tests/10_fastbtc_swap.spec.js, tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js
#Linear Ticket
LIQ-297
https://linear.app/liquality/issue/LIQ-297/need-to-add-terra-chain-option-to-add-custom-token-under-manage-assets
=> fix: Refactor and rename some variables

src/components/LedgerBridgeModal.vue, src/components/OperationErrorModal.vue, src/views/Accounts/HardwareWallet/Unlock.vue
https://linear.app/liquality/issue/LIQ-99/ledger-bridge-connection-management
=> feat: update error messages for ledger

package-lock.json, package.json, src/manifest.json, src/views/CustomToken.vue, tests/e2e/07_add_custom_token.spec.js
feat: Dev wallet 0.49.10
LIQ-507
=> fix: LIQ-507 Custom token validate exists

.github/CODEOWNERS, .github/workflows/pullrequests.yml, .mocharc.yml, package-lock.json, package.json, src/manifest.json, tests/Pages/SwapPage.js, tests/e2e/terra_tests/20_terra_swaps.spec.js
=> feat: Added code owners

src/App.vue
=> fix: blank screen problem solved

.github/CODEOWNERS, renovate.json
https://www.whitesourcesoftware.com/free-developer-tools/renovate/
=> feat: Renovate added

.mocharc.yml, package-lock.json, package.json, src/manifest.json
=> chore: Update cryptoassets package to the latest version

src/swaps/liquality/LiqualitySwapProvider.js
Update terra base gas limit from 650000 to 800000
=> fix: Update terra swap gas limit

.github/workflows/pullrequests.yml, .github/workflows/release.yml
=> feat: PR discord webhook

tests/e2e/07_add_custom_token.spec.js, tests/e2e/terra_tests/23_terra_custom_token.spec.js, tests/pages/AddCustomTokenPage.js
feat: https://linear.app/liquality/issue/LIQ-865/refactor-cutome-token-add-tests
https://linear.app/liquality/issue/LIQ-865/refactor-cutome-token-add-tests
=> feat: LIQ-865 custom token added

package-lock.json, package.json, src/manifest.json, tests/e2e/03_receive.spec.js, tests/e2e/04_send.spec.js, tests/e2e/05_swap.spec.js, tests/e2e/08_custom_fee.spec.js, tests/e2e/14_liquality_booster.spec.js, tests/e2e/15_1inch_swap_provider.spec.js, tests/e2e/16_uniswap_provider.spec.js, tests/e2e/19_private_keys_export.spec.js, tests/e2e/rsk_tests/10_fastbtc_swap.spec.js, tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js, tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js, tests/e2e/terra_tests/19_terra_send.spec.js, tests/e2e/terra_tests/20_terra_swaps.spec.js, tests/pages/OverviewPage.js
…terra-export-private-key
feat: Terra LUNA export private key test
LIQ-883
https://linear.app/liquality/issue/LIQ-883/update-tests-to-add-terra-export-private-key
=> feat: Terra LUNA export private key tests

src/utils/asset.js
=> fix: polygonscan correct url for mumbai testnet

src/components/TransactionList.vue, src/utils/coinFormatter.js, src/views/Swap/ReceiveInput.vue, src/views/Swap/Swap.vue
=> fix: do not show rates when they are missing

src/views/Swap/Swap.vue
=> feat: do not allow swap in boost if user cannot cover fee

.github/CODEOWNERS, .github/workflows/pullrequests.yml, tests/e2e/03_receive.spec.js, tests/e2e/rsk_tests/06_derived_path.spec.js, tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js, tests/pages/PasswordPage.js, tests/pages/SeedWordsPage.js
feat: LIQ-901
[https://linear.app/liquality/issue/LIQ-901/create-wallet-test-failing](url)
=> feat: Create wallet tests fixed

package-lock.json, package.json
Cryptoassets version update to 1.7.2 .
=> chore: cryptoassets to 1.7.2

.github/workflows/build-test-mainnet.yml, .github/workflows/build-test-testnet.yml, .github/workflows/pullrequests.yml, package-lock.json, package.json, src/manifest.json, test/e2e/rsk_tests/rsk_sovryn_amm.spec.js, test/pages/OverviewPage.js
=> test: LIQ-851

src/store/factory/client.js, test/e2e/rsk_tests/06_derived_path.spec.js
=> fix: overrides the near node url for mainnet

src/store/factory/client.js
=> fix: overrides near rpc url

.mocharc.yml, package-lock.json, package.json, src/manifest.json, src/views/Wallet/WalletStats.vue, test/e2e/02_import_wallet.spec.js, test/e2e/swap_tests/01_rbtc_btc_swap.spec.js, test/e2e/terra_tests/20_terra_swaps.spec.js, test/pages/OverviewPage.js
=> fix: fix some failed tests & 0.52.2 release

src/build.config.js, src/store/factory/swapProvider.js, src/store/getters.js, src/swaps/liqualityboost/LiqualityBoostSwapProvider.js, src/swaps/oneinch/OneinchSwapProvider.js, src/utils/asset.js, src/utils/swaps.js
=> Revert "feat: migrate 1inch to v4"

src/build.config.js, src/store/factory/client.js
=> Revert "feat: Update indexer endpoints to new chainhub infra"

src/build.config.js, src/store/factory/client.js
=> Revert "Revert "feat: Update indexer endpoints to new chainhub infra""

src/build.config.js, src/store/factory/swapProvider.js, src/store/getters.js, src/swaps/liqualityboost/LiqualityBoostSwapProvider.js, src/swaps/oneinch/OneinchSwapProvider.js, src/utils/asset.js, src/utils/swaps.js
=> Revert "Revert "feat: migrate 1inch to v4""

src/components/BridgeAssetRequiredMessage.vue, src/components/ListItem.vue, src/views/Account.vue, src/views/Swap/Swap.vue
=> fix: reduce font size of token balance

src/swaps/views/Timeline.vue
=> feat: check failed transactions on timeline diagram

src/components/ConnectionDrawer.vue, src/components/Head.vue, test/e2e/09_menu_options.spec.js, test/e2e/14_liquality_booster.spec.js, test/e2e/17_uniswap_dapp_injection.spec.js, test/e2e/18_sushi_dapp_injection.spec.js, test/e2e/19_private_keys_export.spec.js, test/e2e/rsk_tests/10_fastbtc_swap.spec.js
=> test: refactor dapp tests

src/components/ConnectionDrawer.vue, src/components/Head.vue, src/store/factory/client.js, src/utils/asset.js, src/utils/networks.js, src/views/CustomToken.vue
=> fix: Injection management + lint 

src/components/CustomFeesEIP1559.vue
=> fix: Add watcher for max fee

src/views/Send/Send.vue, src/views/Swap/Swap.vue
=> feat: Enable eip1559 for matic mainnet

src/store/getters.js, src/utils/cryptoassets.js
=> fix: read assets from local cache and also cryptoassets package

src/views/Swap/Swap.vue
=> fix: typo related to merging many branches in dev - resolved

src/views/Swap/Swap.vue
=> fix: double dollar sign ui bug

src/views/Details/SwapDetails.vue, src/views/Details/TransactionDetails.vue
=> fix: Speed up ui changes

test/e2e/03_receive.spec.js, test/e2e/08_custom_fee.spec.js, test/e2e/rsk_tests/06_derived_path.spec.js, test/e2e/rsk_tests/13_rsk_bridge_injection.spec.js, test/e2e/swap_tests/01_rbtc_btc_swap.spec.js, test/e2e/terra_tests/19_terra_send.spec.js, test/pages/OverviewPage.js, test/utils/TestUtils.js
fix: remove some testnet runs and added back to mainnet and PR run
=> test: added some test utils to get the addresses from home screen

package-lock.json, test/e2e/11_oneinch_dapp_injection.spec.js, test/e2e/rsk_tests/06_derived_path.spec.js, test/pages/SeedWordsPage.js
=> test: refactor derivation paths tests

test/e2e/05_swap.spec.js, test/e2e/15_1inch_swap_provider.spec.js, test/e2e/swap_tests/01_rbtc_btc_swap.spec.js, test/pages/SwapPage.js
=> fix: 1inch test to validate fiat values

src/components/CustomFeesEIP1559.vue, src/views/Swap/Swap.vue
=> fix: UI issues from QA report

package-lock.json, package.json, test/e2e/15_1inch_swap_provider.spec.js, test/pages/OverviewPage.js, test/pages/PasswordPage.js, test/pages/SwapPage.js
test: 1inch v4 quote checks / fiat values check
LIQ-990
=> test: LIQ-990

src/store/actions/updateAccountBalance.js, src/store/actions/updateBalances.js, src/store/getters.js, src/views/Details/SwapDetails.vue
=> Fix total fiat balance

src/views/Swap/Swap.vue
=> fix: fix-liq-989-swap-to-rsk-NaN-custom-fee

src/App.vue, src/broker/Background.js, src/broker/Script.js, src/components/Head.vue
=> fix: connection management

src/views/Onboarding/OnboardingSetup.vue
=> fix: wallet flow

src/components/CustomFeesEIP1559.vue
=> feat: Add 2 new tabs for eip1559 transactions

package-lock.json, package.json, src/background.js, src/manifest.json, src/views/PermissionSend.vue, src/views/Swap/Swap.vue
=> refactor: Remove ununsed event labels

src/components/ChainDropdown.vue, src/views/Enable.vue, src/views/PermissionSend.vue, src/views/Swap/Swap.vue, test/e2e/02_import_wallet.spec.js, test/e2e/13_manage_accounts.spec.js, test/e2e/17_uniswap_dapp_injection.spec.js, test/e2e/18_sushi_dapp_injection.spec.js, test/e2e/rsk_tests/13_rsk_bridge_injection.spec.js, test/e2e/terra_tests/21_terra_anchor_dapp.spec.js
=> feat: Improve connection request screen

src/views/ImportWallet.vue, src/views/Onboarding/OnboardingHome.vue, src/views/Onboarding/OnboardingPassword.vue, src/views/Onboarding/OnboardingSetup.vue, src/views/Splash.vue
=> fix: fix routes

test/e2e/13_manage_accounts.spec.js
LIQ-641
Validate filters
Validate Origin url
=> test: LIQ-641 tests added

src/components/CustomFeesEIP1559.vue
=> fix: Label for a total fee

src/store/factory/client.js
=> fix: Use 1559 fee provider for polygon mainnet

src/views/Onboarding/OnboardingPassword.vue
[#LIQ-703](https://linear.app/liquality/issue/LIQ-703/align-pw-creation-step-in-wallet-creation-with-import-flow-and)
=> refactor: password validation

src/background.js
[LIQ-1021](https://linear.app/liquality/issue/LIQ-1021/update-swap-event-with-fromamount-fiatamount)
=> fix: refactor SWAP & SWAP status change events

src/views/Details/SwapDetails.vue
=> feat: show receive fee

package-lock.json, package.json, src/background.js, src/store/factory/client.js, src/views/Enable.vue, test/e2e/08_custom_fee.spec.js
=> fix: updated hw web bridge package

src/transactions/views/Timeline.vue, src/views/Details/TransactionDetails.vue, test/e2e/04_send.spec.js, test/e2e/16_uniswap_provider.spec.js
test: MATIC to MATIC send validations
=> test: LIQ-945

src/views/PermissionSend.vue, src/views/Send/Send.vue, src/views/Swap/Swap.vue
=> fix: Hide eip1559 for Matic on mainnet

src/swaps/thorchain/ThorchainSwapProvider.js
=> fix: added error handling on thorchain swap

.github/workflows/build-test-dev-mainnet.yml, .github/workflows/build-test-prod-mainnet.yml, package-lock.json, package.json, src/manifest.json, src/views/Account.vue, src/views/Swap/Swap.vue, test/e2e/03_receive.spec.js, test/e2e/09_menu_options.spec.js, test/e2e/16_uniswap_provider.spec.js, test/e2e/19_private_keys_export.spec.js, test/e2e/terra_tests/19_terra_send.spec.js, test/e2e/terra_tests/23_terra_custom_token.spec.js
test: some testnet tests removed
test: added prod & dev mainnet tests added
=> chore: Dev 0.54.4

.github/workflows/build-test-dev-mainnet.yml, .github/workflows/build-test-prod-mainnet.yml, .github/workflows/pullrequests.yml, package-lock.json, src/components/ConnectionDrawer.vue, src/components/Head.vue, src/components/WatsNewModal.vue, src/contentScript.js, src/store/migrations/17_remove_injection_enabled.js, src/store/migrations/index.js, src/store/mutations.js, src/store/state.js, test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js, test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js, test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js, test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js, test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js, test/e2e/manage_accounts.spec.js, test/pages/OverviewPage.js
=> fix: default web3 remove dapp toggle

.github/workflows/build-test-dev-mainnet.yml, .github/workflows/build-test-prod-mainnet.yml, .github/workflows/pullrequests.yml, package-lock.json, package.json, src/components/ConnectionDrawer.vue, src/components/Head.vue, src/components/WatsNewModal.vue, src/contentScript.js, src/manifest.json, src/store/migrations/17_remove_injection_enabled.js, src/store/migrations/index.js, src/store/mutations.js, src/store/state.js, test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js, test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js, test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js, test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js, test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js, test/e2e/import_wallet.spec.js, test/e2e/manage_accounts.spec.js, test/pages/OverviewPage.js
=> chore: Release candidate 0.55.0

src/broker/Background.js
=> fix: prevent disconnections from breaking injection

src/components/ActivityFilter.vue
=> fix: Export data

package-lock.json, package.json
Feat: update crypto assets to 1.10.0 - Update list with terra tokens
=> feat: Update-cryptoassets-1.10.0

src/swaps/liquality/LiqualitySwapProvider.js
=> fix: getting quote throw appropriate error

src/swaps/astroport/AstroportSwapProvider.js, src/views/Swap/Swap.vue
=> fix: Min swap rate for astroport

src/swaps/astroport/AstroportSwapProvider.js
=> fix: fix lint issues

.github/workflows/featureArtifact.yml, .github/workflows/pullrequests.yml, .github/workflows/release.yml, src/store/factory/client.js
=> feat: Update terra node

src/swaps/liquality/LiqualitySwapProvider.js
=> fix: Gas limit on terra

src/components/Head.vue, src/components/NavBar.vue, src/store/modules/app/actions.js, src/store/modules/app/getters.js, src/store/modules/app/mutations.js, src/store/modules/app/state.js
fix: Hide menu settings when user click on Connect Dapp
=> fix: Hide menu settings when user click on Connect Dapp

src/build.config.js, src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js, src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js
=> feat: enabled boostprovider for avax

src/store/factory/client.js
=> fix: NEAR ankr mainnet endpoint updated

.env, .github/workflows/release.yml, package-lock.json, package.json, src/store/factory/client.js
=> fix: Hotfix NEAR & TERRA figment endpoints updated

src/broker/terra-injection.js, src/views/PermissionTerra.vue
=> fix: NaN and timeline on terra

src/store/migrations/18_enable_avalanche_chain.js
=> fix: updated migration version of avalanche

src/views/PermissionSend.vue
=> Liq 1068 format send amount

src/components/CustomFees.vue, src/views/Send/Send.vue, src/views/Swap/Swap.vue
=> fix: scientific values removed from ui

src/views/Swap/ReceiveInput.vue, src/views/Swap/SendInput.vue, src/views/Swap/Swap.vue
=> feat: Reverse assets on arrow click and keep same from amount on asset change

src/store/migrations/18_enable_avalanche_chain.js, src/views/Swap/Swap.vue
=> fix: avalanche migration version

src/build.config.js, src/swaps/astroport/AstroportSwapProvider.js, src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js, src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js, src/swaps/oneinch/OneinchSwapProvider.js, src/utils/fees.js
=> feat: add Astroport in Boosts

src/store/mutations.js, src/utils/asset.js, src/views/Swap/Swap.vue
[LIQ-1192](https://linear.app/liquality/issue/LIQ-1192/disabling-btc-will-break-swap-feature)
=> fix: correct deafult asset logic

src/build.config.js, src/swaps/astroport/AstroportSwapProvider.js, src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js, src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js, src/swaps/oneinch/OneinchSwapProvider.js, src/utils/fees.js
=> Revert "feat: add Astroport in Boosts"

src/build.config.js
=> fix: temporary disable erc20<>native boost swap

package-lock.json, package.json, src/build.config.js, src/manifest.json
=> fix: Release candidate 0.60.0

src/build.config.js
=> fix: enable erc to native boost swaps

src/views/Swap/Swap.vue
=> fix: improved logic  for amm validation

src/broker/terra-injection.js, src/components/AnalyticsOptInModal.vue, src/views/Onboarding/OnboardingHome.vue, test/pages/HomePage.js, test/pages/PasswordPage.js
[#LIQ-768](https://linear.app/liquality/issue/LIQ-768/streamline-onboarding-experience)
=> streamline onboarding experience

src/broker/terra-injection.js, src/views/Details/SwapDetails.vue
[#LIQ-1285](https://linear.app/liquality/issue/LIQ-1253/fee-amount-is-shown-as-luna-when-making-a-ust-atomic-swap-typo-ui)
=> fix unit for UST swaps

src/views/Swap/Swap.vue, src/views/Swap/SwapInfo.vue
[LIQ-1313](https://linear.app/liquality/issue/LIQ-1313/minimal-amounts-improvements)
=> Improve minimal amounts

package.json, src/swaps/views/Timeline.vue, yarn.lock
Moves timeline function to `wallet-core`
=> refactor: Use timeline from wallet-core

package.json, src/background.js, src/components/ConnectionDrawer.vue, src/components/NavBar.vue, src/components/WatsNewModal.vue, src/views/Account.vue, src/views/Accounts/HardwareWallet/HardwareWallet.vue, src/views/Onboarding/SeedPhrase/LoginPhrase.vue, src/views/Receive.vue, src/views/Send/Send.vue, src/views/Settings.vue, src/views/Swap/Swap.vue, src/views/UnlockWallet.vue, yarn.lock
=> feat: Release candidate 0.62.2.

package.json, yarn.lock
Fixes the issue where if a provider's market data update fails, all others are not updated
=> fix: Update wallet core - fixes market data failing

src/components/CustomFeesEIP1559.vue, src/views/CustomToken.vue, src/views/Details/TransactionDetails.vue, src/views/Send/Send.vue
[LIQ-1213](https://linear.app/liquality/issue/LIQ-1213/wallet-and-cryptoassets-minor-refactoring)
Dependencies form Cryptoassets:
https://github.com/liquality/cryptoassets/pull/81
https://github.com/liquality/cryptoassets/pull/82
=> refactor: send fee

package.json, src/inject.js, src/manifest.json
=> feat: hotfix missing injection interface

src/views/Swap/Swap.vue
=> Revert "feat: improve minimum amount logic for boosts"

src/views/Swap/Swap.vue
=> Revert "feat: prevent zero error for non dollar value assets"

src/components/CustomFeesEIP1559.vue, src/views/CustomToken.vue, src/views/Details/TransactionDetails.vue, src/views/Send/Send.vue
=> Revert "refactor: send fee"

src/broker/terra-injection.js, src/components/WalletAccounts.vue, src/store/modules/app/requestPermission.js, src/views/CustomToken.vue, src/views/Send/Send.vue
=> Revert "refactor: using enums instead of strings for chain names"

src/components/AnalyticsOptInModal.vue
- both create wallet / import wallet YES should select by default
=> feat: set default to yes for analytics opt-in yes LIQ-1412

src/views/Receive.vue
https://linear.app/liquality/issue/LIQ-1472/[amplitude]-fix-receive-copy-address-chain-details-in-the-properties
=> fix: LIQ-1472 - Receive copy address chain property fix

src/assets/scss/style.scss, src/components/BoostActivateBridgeAsset.vue, src/components/BridgeAssetRequiredMessage.vue, src/components/CannotCoverMinimumMessage.vue, src/components/EthRequiredMessage.vue, src/components/NoFundsForNetworkFee.vue, src/components/NoLiquidityMessage.vue, src/views/Swap/SendInput.vue, src/views/Swap/Swap.vue, src/views/Swap/SwapInfo.vue, test/pages/SwapPage.js
=> Liq 1205/error messaging chainify

src/broker/terra-injection.js, src/store/modules/app/executeRequest.js
=> fix: terra injection

src/views/Details/TransactionDetails.vue, src/views/PermissionSend.vue, src/views/Send/Send.vue, src/views/Swap/Swap.vue
[LIQ-1273](https://linear.app/liquality/issue/LIQ-1273/max-send-eth-not-working)
=> feat: change eip1559 calculation formula

package.json, yarn.lock
=> feat: updated wallet-core version in package json

package.json, src/components/WhatsNewModal.vue, yarn.lock
* wallet-core bump version to 1.7.1 from 1.6.0
* Update the whats new model section
=> feat: whats new model update

src/views/Onboarding/OnboardingSetup.vue, src/views/Onboarding/SeedPhrase/ConfirmSeed.vue
=> fix: seed confirmation with repeating words

src/contentScript.js, src/inject.js
=> fix: ensure injection without default web3. more reliable

src/views/Swap/Swap.vue, src/views/Swap/SwapInfo.vue
=> fix: text shorten issue

src/components/Modal.vue, src/views/Swap/Swap.vue, src/views/Swap/SwapProvidersInfoModal.vue
=> fix: fixed default fee and swap provider types modal height

test/e2e/transak_tests/new_wallet_user_buy_crypto.spec.js
feat: OPS-3 tests
https://linear.app/liquality/issue/OPS-3/[buy-crypto]-wallet-automated-tests
=> test: buy crypto tests OPS-3

src/components/BoostActivateBridgeAsset.vue, src/components/BridgeAssetRequiredMessage.vue, src/components/CannotCoverMinimumMessage.vue, src/components/EthRequiredMessage.vue, src/components/LedgerRequestMessage.vue, src/components/NoFundsForNetworkFee.vue
=> fix: remove unused spacing on notifications

src/components/WalletAccounts.vue
=> fix: check for initial load on balances

src/views/Swap/Swap.vue
=> fix: removed outdated validation

package.json, src/views/Swap/Swap.vue, yarn.lock
=> feat: update wallet core version and rounding fix

package.json, src/views/CustomToken.vue, src/views/PermissionSend.vue, yarn.lock
Merge after https://github.com/liquality/wallet-core/pull/108
=> fix: refactor fetching token details

test/e2e/solana_tests/solana_swaps.spec.js
=> Automation tests for solana swaps

vue.config.js
=> fix: remove split chunks in prod

package.json, src/components/FeeSelector.vue, src/components/WalletAccounts.vue, src/swaps/views/Timeline.vue, src/transactions/views/Timeline.vue, src/views/Accounts/Create.vue, src/views/Accounts/HardwareWallet/HardwareWallet.vue, src/views/Details/NFTTransactionDetails.vue, src/views/Details/SwapDetails.vue, src/views/PermissionSend.vue, src/views/Send/Send.vue, yarn.lock
- #EXT-68 Ledger Create screen issue
- #EXT-72 Address format inside timeline
=> fix: fixed ledger create account flow

src/transactions/views/Timeline.vue
=> fix: timeline diagram for non-evm chains

src/components/NavBar.vue
=> fix: hide export private key option for Bitcoin accounts

src/views/Details/NFTAssetDetails.vue, src/views/Send/SendNFT.vue
[#EXT-77](https://linear.app/liquality/issue/EXT-77/network-fee-is-always-zero-in-nft-send-screen)
=> Ext 77 network fee is always zero in nft send

src/components/FeeSelector.vue, src/components/NavBar.vue, src/views/Details/NFTTransactionDetails.vue, src/views/PermissionSend.vue
[#EXT-48](https://linear.app/liquality/issue/EXT-48/apply-and-cancel-button-not-working-on-clicking-custom-button-sovryn)
=> Ext 48 apply and cancel button not working on

src/broker/Background.js, src/contentScript.js, src/views/PermissionSignPsbt.vue, test/unit/solana.test.js
=> fix: injection and other uses of chain networks

src/locales/cb/terms.html, src/locales/es/terms.html, src/locales/ph/terms.html, src/locales/pt/terms.html, src/locales/zh/terms.html
=> fix: added back terms.html for all languages

src/locales/es/common.json, src/locales/ph/common.json, src/locales/pt/common.json, src/locales/zh/common.json
=> fix: added missing translation keys

src/contentScript.js
Toggling this off was not working:
=> fix: override should only happen when enabled

src/contentScript.js
=> fix: injection should still work if not overriding

package.json, src/broker/Background.js, src/store/modules/app/executeRequest.js, src/swaps/views/Timeline.vue, src/transactions/views/Timeline.vue, src/views/Details/NFTTransactionDetails.vue, src/views/Details/TransactionDetails.vue, src/views/PermissionSignPsbt.vue, src/views/Receive.vue, yarn.lock
=> fix: assets must be fetched from store instead of cryptoassets

src/locales/en/pages.json
https://linear.app/liquality/issue/EXT-112
=> Fixes Linear EXT-112

src/App.vue, src/components/WhatsNewModal.vue, src/store/modules/app/actions.js, src/store/modules/app/mutations.js, src/store/modules/app/state.js
- remove firebase feature
- move what's new modal content to app file to load faster
=> fix: what's new modal 

.github/workflows/pullrequests.yml, test/e2e/dapp_injection_tests/dapp_injection.spec.js
INF-36
https://linear.app/liquality/issue/INF-36/wallet-remove-deprecated-actions-and-upgrade-ci
=> ci: upgrade github actions

src/manifest.json
=> feat: Self-Custodial Multi-Chain Wallet that is 100% Open Source INF-38

package.json, src/components/NFT/NFTAsset.vue, src/views/Details/NFTAssetDetails.vue, yarn.lock
=> fix: nft collection item not opening correctly

src/views/Swap/SwapProvidersInfoModal.vue
=> Remove liquality atomic swaps

src/views/Swap/Swap.vue
[LIQ-189](https://linear.app/liquality/issue/EXT-189/p2-swap-matic-to-eth-swap-seems-to-be-unsupported-pair-until-user)
=> Updated defaultAmount to max

src/pageProvider/ethereumProvider.js
=> Fix cor 57 send transaction response from injection

src/locales/cb/common.json, src/locales/cb/components.json, src/locales/cb/pages.json, src/locales/es/common.json, src/locales/es/components.json, src/locales/es/pages.json, src/locales/ph/common.json, src/locales/ph/components.json, src/locales/ph/pages.json, src/locales/pt/common.json, src/locales/pt/pages.json, src/locales/zh/common.json, src/locales/zh/pages.json
Latest crowdin files for RC 0.79.0
=> Updating locale files from crowdin

src/components/WalletAccounts.vue, src/views/Swap/Swap.vue, src/views/Swap/SwapProvidersInfoModal.vue
=> Fixing small check for NFTs 

src/views/CustomToken.vue
=> Enable decimal field customisation on pulling data from external token

src/views/Details/NFTAssetDetails.vue
=> fix SOL NFTs not showing

package.json, src/locales/cb/desc.md, src/locales/cb/messages.json, src/locales/en/desc.md, src/locales/en/messages.json, src/locales/es/desc.md, src/locales/es/messages.json, src/locales/ph/desc.md, src/locales/ph/messages.json, src/locales/pt/desc.md, src/locales/pt/messages.json, src/locales/zh/desc.md, src/locales/zh/messages.json, src/manifest.json, vue.config.js, yarn.lock
=> feat: implemented chrome store multilang support

src/locales/en/whats_new.json
We still need to add latest translated files from Crowdin.
=> Update to what's new in 0.80.0

src/views/CustomToken.vue
This PR Fiexes
- The 0 issue
- The errors shown when adding a custom token
- And the input issue where we needed to only accept numbers
=> Error fixes while adding a custom token

src/views/Swap/Swap.vue
This PR fixes the Solana fees issue
=> Solana fees fix

src/views/Swap/Swap.vue
=> Removing console logs

src/views/Swap/Swap.vue, src/views/Wallet/WalletStats.vue
=> Assets count fix

src/locales/cb/common.json, src/locales/es/common.json, src/locales/ph/common.json, src/locales/pt/common.json, src/locales/zh/common.json
https://linear.app/liquality/issue/EXT-165/
=> Add new string to other languages

src/pageProvider/ethereumProvider.js
=> chore: set metamask emulated = true by default

src/components/Head.vue, src/views/Account.vue
=> Activity filter fix

src/components/Head.vue, src/views/Account.vue
=> Ext 182/account address copy message fix

src/views/Details/NFTAssetDetails.vue
=> Ext 238 | Ethereum nft IPFS image fix

src/swaps/views/Timeline.vue
=> Error message display fix

src/locales/en/common.json, src/views/Send/Send.vue, src/views/Send/SendInput.vue
=> Set minimum amount that can be sent and prevent dust transactions

src/locales/en/common.json, src/views/Send/Send.vue, src/views/Send/SendInput.vue
=> Refactor Minimum Send amount alert to use warning alert

package.json, src/main.js, src/manifest.json, src/views/Send/Send.vue
=> fix: modified login to validate min send amount for solana and btc

src/views/Send/Send.vue
=> fix: fixed commented required gas message

package.json, src/locales/cb/terms.html, src/locales/es/terms.html, src/locales/ph/terms.html, src/locales/pt/terms.html, src/locales/zh/terms.html, src/manifest.json
=> fix: updated locale files / terms and conditions

src/views/Details/NFTAssetDetails.vue
=> IPFS image url fix

package.json, src/components/NavBar.vue, src/manifest.json, src/views/Experiments.vue, yarn.lock
=> feat: enabled by default manage accounts

src/swaps/views/Timeline.vue, src/views/Account.vue, src/views/Send/SendNFT.vue, src/views/Wallet/NFTActivity.vue
=> EXT-223 | Account Activity filter fixes and Polygon error fix

package.json, src/manifest.json, src/views/Send/SendNFT.vue, src/views/Wallet/NFTActivity.vue, yarn.lock
=> fix: some fixes for nft screens

src/components/CustomRpcSettingsForm.vue, src/components/NavBar.vue, src/locales/cb/pages.json, src/locales/en/pages.json, src/locales/es/pages.json, src/locales/ph/pages.json, src/locales/pt/pages.json, src/locales/zh/pages.json, src/views/Accounts/Manage.vue, src/views/SettingItems.vue
This PR Fixes issues;
- Add Manage Accounts button inside settings (Should look like the Networks option)
- We should show the full address a user has entered instead of cutting it off.
- Double check to make sure that a user cannot edit the disabled fields
=> Ext 256/custom rpc settins form fix

src/views/Receive.vue, src/views/Send/Send.vue
=> EXT-253 | Receive Screen error fix

src/views/Account.vue
=> EXT-257 | Copy address tooltip inside Asset fix

src/views/UnlockWallet.vue
=> Password error message fix

package.json, src/components/Modal.vue, src/locales/cb/common.json, src/locales/cb/pages.json, src/locales/en/common.json, src/locales/en/pages.json, src/locales/es/common.json, src/locales/es/pages.json, src/locales/ph/common.json, src/locales/ph/pages.json, src/locales/pt/common.json, src/locales/pt/pages.json, src/locales/zh/common.json, src/locales/zh/pages.json, src/manifest.json, src/views/PermissionSign.vue
=> fix: fixed permission sign screen for eip 712 and v1

package.json, src/locales/cb/pages.json, src/locales/cb/whats_new.json, src/locales/en/pages.json, src/locales/en/whats_new.json, src/locales/es/pages.json, src/locales/es/whats_new.json, src/locales/ph/pages.json, src/locales/ph/whats_new.json, src/locales/pt/pages.json, src/locales/pt/whats_new.json, src/locales/zh/pages.json, src/locales/zh/whats_new.json, src/manifest.json, src/views/PermissionSign.vue
=> fix: fixes for EIP-712 injection
